### PR TITLE
Integrated mms into simulation.jl functions

### PR DESCRIPTION
**Pull request by dere4**
a lot of commits but most of them didnt change much since I forgot to select the changes to commit. basically added a few terms to simulation tuple to facilitate mms. Uses boolean MMS to select actions in the simulation.jl functions and mms! for the actual terms to be added on the RHS. both are stored at MMS, mms! = params.mms .

### CODE REVIEW

**Comment by archermarx** [comment]
there's some failing tests, should make those pass before merging. you can check the output of the CI runs to see, but the simulation setup tests fail now and i would expect the freestream preservation test does too. both should be straightforward to fix.

**Comment by dere4** [comment]
I updated dere4:main, the tests are fixed and mms is included, I think this pull requested was updated with it. cant create another one.

**Comment by archermarx** [comment]
Yep, this PR has been updated. Now waiting for tests to run

**Comment by dere4** [comment]
added symbolics, which added a line to project.toml

**Comment by dere4** [comment]
somehow I need to always commit twice

**Comment by dere4** [comment]
added all packages I could find were included and missing. Added convergence to MMS, will now run either up to convergence or end time, is using callback TerminateSteadyState. https://diffeq.sciml.ai/stable/features/callback_library/
determines whether 1st derivatives are sufficiently small, used default values for now. Verified that it actually works, ie with the callback simulations stop earlier when giving sufficiently long end_time.

**Comment by archermarx** [comment]
tests are passing, I'll take a look through the code

**Comment by archermarx** [comment]
looks great, merging now

**Pull request merged**
