### PR TITLE
Made tests pass

### PR DESCRIPTION
**Pull request by dere4**

### CODE REVIEW

**Comment by archermarx** [comment]
evidently there's something wrong with the documentation building. i'll looki into that

**Comment by archermarx** [comment]
1.6 is failing due to a manifest file compatibility issue. Since we're using 1.6 stuff it's probably good if we just remove those tests.

**Comment by archermarx** [comment]
> evidently there's something wrong with the documentation building. i'll looki into that

There's some package problem with AbbreviatedStackTraces. I suspect it's because it's not a registered package.

**Comment by dere4** [comment]
think problem wasnt abbrstacktraces, but missing _ in doctest setup for conservation laws

**Comment by archermarx** [comment]
> think problem wasnt abbrstacktraces, but missing _ in doctest setup for conservation laws

oh interesting, that makes sense since i changed from symbols to enums. the issue in the documentation build failure said something about unsatisfiable requirements. this is a different issue than the doctests, so hopefully both are fixed now.

**Comment by dere4** [comment]
oh yeah I didnt realise the documentation test is a whole different thing, was just thinking about doctests. yh if abbrstacktraces was the issue it should work now

**Comment by dere4** [comment]
interesting that codecov decreased so much, dont understand why. can you open it at codecov? throws me an error

**Comment by archermarx** [comment]
documentation is fixed now.

**Comment by archermarx** [comment]
> interesting that codecov decreased so much, dont understand why. can you open it at codecov? throws me an error

lets wait for tests to pass then i'll look into it

**Comment by archermarx** [comment]
Tests pass! Will look into codecov in a few

**Pull request merged**
