### PR TITLE
Can be merged, tests passing

### PR DESCRIPTION
**Pull request by dere4**
Simulation not very stable, solves but takes very long time. 
still extreme oscillations in energy, not physical result. 
initial conditions, BCs and potential drop correspond to landmark. 
but no ion recombination at anode. 

added a bunch of variables to state vector, still
get very strong oscillations in energy,
tried to find cause,
electron velocity oscillating between +- 200000 in the first few cells.
tried to find cause of that, grad phi looks good, grad epsilon
oscillates but not as strong. need to check
electron transport, which in turn is dependent on neutral density
through v_c, which does not seems like it
oscillates though.

### CODE REVIEW

**Comment by dere4** [comment]
Tests are passing now, feel free to merge. In the simulation struct there is a Bool field solve_energy, through which either a SplitODEprob is solved, or as before just a ODEprob if set to false. That is how the tests are done for now. Added some stuff to state vector, some information is present a couple of times, its mainly to help me figure out what is going on. Also multiple ion fluids should be running again now (not with landmark source terms but otherwise). The run_sim function uses boundaries and ICs of landmark, not ion recombination yet or Bohm condition though. 

For the energy equ., I just noticed that I get oscillations after one timestep even if not updating fluxes or using energy source term, so there is something going on. Have some ideas that I will try.

**Comment by dere4** [comment]
Things are a bit inconsistent as of now, energy is in [eV], pressure/energy pe is in [J], and neutrals and ion density should be implemented in kg/m^3, while n\epsilon (the conserved internal energy solved for the electron equation) is [1/m^3*eV]. Will change this and experiment with using old vs new value of pe in convective flux and neglect/not neglect factor 3/2.

**Comment by dere4** [comment]
btw I'm using Julia Version 1.6.3. is that an issue with some of the checks you set up?

**Comment by archermarx** [comment]
You should upgrade to 1.7, but the latest 1.6 version is 1.6.5 so we should make sure that works as well. The 1.6 test failed but i'm not sure why

**Pull request merged**
